---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: debian-8.2
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[ts3_cookbook::default]
    attributes:
